@startuml Redis_Auth_Storage

skinparam title {
    FontSize 18
}

skinparam object {
    BackgroundColor White
    BorderColor Black
    ArrowColor Black
}

title Redis: Auth Service

object "auth:verify:email:otp:{verify_token}" as EmailOTP {
    -- Key Info --
    **type** = "Hash"
    **ttl** = "5 minutes"
    -- Fields --
    .. User Identities ..
    * **user_id**: UUID
    * **email**: String(320)
    .. Security Context ..
    * **user_agent**: TEXT
    * **fingerprint_hash**: String(64)
    .. Verification ..
    * **code_hash**: String(64)
    * **attempts**: Integer
}

object "auth:verify:session:{mfa_token}" as MFASession {
    -- Key Info --
    **type** = "Hash"
    **ttl** = "5 minutes"
    -- Fields --
    .. User Identities ..
    * **user_id**: UUID
    .. Security Context ..
    * **user_agent**: TEXT
    * **fingerprint_hash**: String(64)
    .. Flow State ..
    * **method**: String ('EMAIL', 'TOTP', 'BACKUP_CODES')
    * **attempts**: Integer
}

object "auth:limiter:{endpoint}:ip:{ip}" as LimiterIp {
    -- Key Info --
    **type** = "String"
    **ttl** = "600 seconds"
    -- Value --
    * **attempts**: Integer
}

object "auth:limiter:{endpoint}:fp:{fp}" as LimiterFP {
    -- Key Info --
    **type** = "String"
    **ttl** = "60 seconds"
    -- Value --
    * **attempts**: Integer
}

object "auth:limiter:user:{endpoint}:{user_id/email_hash}" as LimiterUser {
    -- Key Info --
    **type** = "String"
    **ttl** = "60 seconds"
    -- Value --
    * **attempts**: Integer
}

object "auth:lockout:user:{user_id}" as Lockout {
    -- Key Info --
    **type** = "String"
    **ttl** = "15 minutes"
    -- Value --
    * **attempts**: Integer
}

@enduml